version: '3.8'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: iconichash_frontend
    ports:
      - '3038:3038'
    restart: on-failure
  nginx:
    container_name: proxy_nginx
    depends_on:
      - client
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always